// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final boolean TUNING = true;
    public static final int SLOT_INDEX = 0;
    public static class FlywheelConstants{
        public static final int kSlotIdx = 0;
        public static final int kPIDLoopIdx = 0;
        public static final int kTimeoutMs = 30;
        public static final int VELOCITY_TOLERANCE = 0; //FIX_ME tune this should be how off our velocity can be 
        


    public final static Gains kGains_Velocit  = new Gains( .74,      0,   0,    .05265,        0,    1.00);

   }
   public class HoodConstants{
       public static final int HOOD_P = 0; //FIX_ME find hood pid p value 

   }

   public class LimelightConstants {
       public static final double HUB_H = 104;
       public static final double ROBOT_H = 21.25;
       public static final double GRAV_CONST_FT = -32.17519788;
       public static final int LIMELIGHT_ANGLE_OFFSET=-2;
       public static final int D2_D1_OFFSET = 2;
       public static final int H2_H1_OFFSET = -2;
   }

}

