// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.networktables.NetworkTableEntry;
import frc.robot.Constants;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.TalonFXControlMode;
import com.ctre.phoenix.motorcontrol.TalonFXFeedbackDevice;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Flywheel extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonFX talonLeft;
private WPI_TalonFX talonRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private double velocitySetPoint;

    private NetworkTableEntry rightEncoderReadingNT;
    private NetworkTableEntry leftEncoderReadingNT;
    private NetworkTableEntry rightClosedLoopErrorNT;
    private NetworkTableEntry leftClosedLoopErrorNT;

    /**
    *
    */
    public Flywheel() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
talonLeft = new WPI_TalonFX(1);
 
 

talonRight = new WPI_TalonFX(2);
 
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        this.talonLeft.setInverted(true);

        /* Factory Default all hardware to prevent unexpected behaviour */
        this.talonRight.configFactoryDefault();
        this.talonLeft.configFactoryDefault();

        /* Config neutral deadband to be the smallest possible */
        this.talonRight.configNeutralDeadband(0.001);
        this.talonLeft.configNeutralDeadband(0.001);

        /* Config sensor used for Primary PID [Velocity] */
        this.talonRight.configSelectedFeedbackSensor(TalonFXFeedbackDevice.IntegratedSensor,
                Constants.FLYWHEEL_SLOT_INDEX,
                Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.configSelectedFeedbackSensor(TalonFXFeedbackDevice.RemoteSensor0,
                Constants.FLYWHEEL_SLOT_INDEX,
                Constants.FLYWHELL_TIMEOUT_MS);

        /* Config the peak and nominal outputs */
        this.talonRight.configNominalOutputForward(0, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.configNominalOutputReverse(0, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.configPeakOutputForward(1, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.configPeakOutputReverse(-1, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.configNominalOutputForward(0, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.configNominalOutputReverse(0, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.configPeakOutputForward(1, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.configPeakOutputReverse(-1, Constants.FLYWHELL_TIMEOUT_MS);

        /* Config the Velocity closed loop gains in slot0 */
        this.talonRight.config_kF(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kF, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.config_kP(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kP, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.config_kI(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kI, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonRight.config_kD(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kD, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.config_kF(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kF, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.config_kP(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kP, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.config_kI(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kI, Constants.FLYWHELL_TIMEOUT_MS);
        this.talonLeft.config_kD(Constants.FLYWHEEL_SLOT_INDEX, Constants.FLYWHEEL_VELOCITY_GAINS.kD, Constants.FLYWHELL_TIMEOUT_MS);
        /*
         * Talon FX does not need sensor phase set for its integrated sensor
         * This is because it will always be correct if the selected feedback device is
         * integrated sensor (default value)
         * and the user calls getSelectedSensor* to get the sensor's position/velocity.
         * 
         * https://phoenix-documentation.readthedocs.io/en/latest/ch14_MCSensor.html#
         * sensor-phase
         */
        // this.talonRight.setSensorPhase(true);

        this.velocitySetPoint = 0.0;

        this.rightEncoderReadingNT = Shuffleboard.getTab("Shooter")
                .add("FlywheelRightEncoderReading", 0.0)
                .getEntry();
        this.leftEncoderReadingNT = Shuffleboard.getTab("Shooter")
                .add("FlywheelLeftEncoderReading", 0.0)
                .getEntry();

        this.rightClosedLoopErrorNT = Shuffleboard.getTab("Shooter")
                .add("FlywheelRightClosedLoopError", 0.0)
                .getEntry();
        this.leftClosedLoopErrorNT = Shuffleboard.getTab("Shooter")
                .add("FlywheelLeftClosedLoopError", 0.0)
                .getEntry();

    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        this.rightEncoderReadingNT.setDouble(this.talonRight.getSelectedSensorVelocity(Constants.FLYWHEEL_SLOT_INDEX));
        this.leftEncoderReadingNT.setDouble(this.talonLeft.getSelectedSensorVelocity(Constants.FLYWHEEL_SLOT_INDEX));
        this.rightClosedLoopErrorNT.setDouble(this.talonRight.getClosedLoopError(Constants.FLYWHEEL_SLOT_INDEX));
        this.leftClosedLoopErrorNT.setDouble(this.talonLeft.getClosedLoopError(Constants.FLYWHEEL_SLOT_INDEX));

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public double getVelocity() {
        return this.talonLeft.getSelectedSensorVelocity(Constants.FLYWHEEL_SLOT_INDEX);
    }

    public void setVelocity(double velocitySetPoint) {
        this.velocitySetPoint = velocitySetPoint;

        talonLeft.set(TalonFXControlMode.Velocity, velocitySetPoint);
        talonRight.set(TalonFXControlMode.Velocity, velocitySetPoint);
    }

    public boolean isAtSetpoint() {
        return Math.abs(this.getVelocity() - this.velocitySetPoint) < Constants.FLYWHEEL_VELOCITY_TOLERANCE;
    }

    public void stopFlywheel() {
        talonLeft.set(TalonFXControlMode.PercentOutput, 0.0);
        talonRight.set(TalonFXControlMode.PercentOutput, 0.0);
    }

}
