// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import static frc.robot.Constants.*;

import java.util.Map;


import edu.wpi.first.wpilibj.shuffleboard.BuiltInWidgets;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.ControlMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.networktables.EntryListenerFlags;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Storage extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX storage4;
private DigitalInput collectorSensor0;
private DigitalInput shooterSensor1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Storage() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    storage4 = new WPI_TalonSRX(StorageConstants.STORAGE_MOTOR_ID);
 
 

    collectorSensor0 = new DigitalInput(StorageConstants.COLLECTOR_SENSOR);
    addChild("Collector Sensor 0",collectorSensor0);
 

    shooterSensor1 = new DigitalInput(StorageConstants.SHOOTER_SENSOR);
    addChild("Shooter Sensor 1",shooterSensor1);
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    Shuffleboard.getTab("Storage").addBoolean("Collector Unblocked", this::isCollectorSensorUnblocked);
    Shuffleboard.getTab("Storage").addBoolean("Shooter Unblocked", this::isShooterSensorUnblocked);
    
    if(TUNING) {
        // Each robot feature that requires PID tuniing has its own Shuffleboard tab for
        // tuning (i.e., "ShooterTuning")
        // Add indicators and controls to this Shuffleboard tab to assist with
        // interactively tuning the system.

        Shuffleboard.getTab("Storage")
                .add("Storage Power", 0.0)
                .withWidget(BuiltInWidgets.kNumberSlider)
                .withProperties(Map.of("min", -1.0, "max", 1.0)) // specify widget properties here
                .getEntry()
                .addListener(event -> {
                this.setStoragePower(event.getEntry().getValue().getDouble());
                }, EntryListenerFlags.kNew | EntryListenerFlags.kUpdate);
    }
}
    

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void setStoragePower(double power){
        this.storage4.set(ControlMode.PercentOutput, power);
    }

    public void enableStorage(){ 
        this.storage4.set(ControlMode.PercentOutput, StorageConstants.STORAGE_DEFAULT_SPEED);
    }

    public void disableStorage() {
        this.storage4.set(ControlMode.PercentOutput, 0);   
    }

    public boolean isShooterSensorUnblocked(){
        return this.shooterSensor1.get();
    }

    public boolean isCollectorSensorUnblocked(){
        return this.collectorSensor0.get();
    }

    public double getStoragePower(){
        return this.storage4.get();
    }
}

