// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final boolean TUNING = true;
    public static final int SLOT_INDEX = 0;
    public static class ElevatorConstants{

        //FIXME these encoder values need to be tuned
        public static final double MAX_ELEVATOR_HEIGHT = 283089;
        public static final double MIN_DETACH_ENCODER_HEIGHT = 0;
        public static final double MIN_ELEVATOR_ENCODER_HEIGHT = 0;
        public static final double MID_RUNG_HEIGHT = 277129;
        public static final double REACH_TO_NEXT_RUNG_HEIGHT = 0; // not sure if this is needed; use MAX_ELEVATOR_HEIGHT?
        public static final double PITCH_SETPOINT = 0;
        public static final double PITCH_TOLERANCE =  0;
        public static final int ELEVATOR_POSITION_TOLERANCE = 0;
        public static final double ARBITRARY_FEED_FORWARD_EXTEND = .02;
        public static final double ARBITRARY_FEED_FORWARD_RETRACT = -0.07;
        public static final double DEFAULT_MOTOR_POWER = 0;

        //FIXME Talon Config, these values from flywheel
        public static final int kSlotIdx = 0;
        public static final int kPIDLoopIdx = 0;
        public static final int kTimeoutMs = 30;
        public static final Gains GAINS_POSITION  = new Gains( 0 /* kP */, 0 /* kI */, 0 /* kD */, 0 /* kF */, 0 /* kIZone */, 1.00 /* max output */);
        //FIXME additional config
        public static final double MAX_ELEVATOR_VELOCITY = 21305.0 / 2;  // theoretical maximum 21305
        public static final double ELEVATOR_ACCELERATION = MAX_ELEVATOR_VELOCITY / 2;
        public static final int SCURVE_STRENGTH = 0;
       
        //CAN ID
        public static final int PIGEON_ID = 18;
        public static final int LEFT_ELEVATOR_MOTOR_CAN_ID = 22;
        public static final int RIGHT_ELEVATOR_MOTOR_CAN_ID = 19;

  }
    public class SecondMechanismConstants { 
        public static final int PNEUMATIC_HUB_CAN_ID = 20;
        public static final int PNEUMATIC_CHANNEL = 0;
  }
}

