// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final boolean TUNING = true;
    public static final int TEST = 0;
    public static final int SLOT_INDEX = 0;
    public static class ElevatorConstants{
        public static final double MAX_ELEVATOR_ENCODER_HEIGHT = 0; //FIX_ME find the max elevator height encoder value
        public static final double MIN_ELEVATOR_ENCODER_HEIGHT = 0;
        public static final double SECOND_RUNG_ENCODER_HEIGHT = 0;//FIX_ME the height the elevator should be at to get on the second rung
        public static final double THIRD_RUNG_ENCODER_HEIGHT = 0;//FIX_ME the Height the elevator should be at to get from second to third rung
        public static final double FOURTH_RUNG_ENCODER_HEIGHT = 0;//FIX_ME the height the elevator should be at to get from the third to fourth rung
        public static final double ELEVATOR_MOTOR_POWER = 0; //FIX_ME find what we want the elevator motor power to be(maybe the max?)
        public static final int LEFT_ELEVATOR_MOTOR_CAN_ID = 18;
        public static final int RIGHT_ELEVATOR_MOTOR_CAN_ID = 19; 
        public static final int kSlotIdx = 0;
        public static final int kPIDLoopIdx = 0;
        public static final int kTimeoutMs = 30;
        public static final int ELEVATOR_POSITION_TOLERANCE = 0; //FIX_ME tune this should be how off our velocity can be 
        public final static Gains kGains_Velocit  = new Gains( .74,      0,   0,    .05265,        0,    1.00);
  }
    public class SecondMechanismConstants { 
        public static final int PNEUMATIC_HUB_CAN_ID = 20;
        public static final boolean SECOND_MECHANISM_PULL = true;
        public static final boolean SECOND_MECHANISM_PUSH = false;
  }
}

